default:
  http_metas:
    content-type: text/html

  metas:
    title:        LandnCall Admin Portal
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [admin.css, ../sf/sf_admin/css/admin_main.css, backend.css]

  javascripts:    [/sf/prototype/js/prototype.js, jquery-1.4.2.min.js,jquery.validate1.js, main.js]

  has_layout:     on
  layout:         layout
