<?php


/**
 * This class adds structure of 'enable_country' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 01/11/12 05:25:24
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EnableCountryMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EnableCountryMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(EnableCountryPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(EnableCountryPeer::TABLE_NAME);
		$tMap->setPhpName('EnableCountry');
		$tMap->setClassname('EnableCountry');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 200);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 300);

		$tMap->addColumn('LANGUAGE', 'Language', 'VARCHAR', true, 300);

		$tMap->addColumn('LANGUAGE_SYMBOL', 'LanguageSymbol', 'VARCHAR', true, 300);

		$tMap->addColumn('CURRENCY', 'Currency', 'VARCHAR', true, 300);

		$tMap->addColumn('CURRENCY_SYMBOL', 'CurrencySymbol', 'VARCHAR', true, 300);

		$tMap->addForeignKey('STATUS', 'Status', 'INTEGER', 'status', 'ID', true, 10);

		$tMap->addColumn('CEATED_AT', 'CeatedAt', 'TIMESTAMP', true, null);

		$tMap->addColumn('BASE_URL', 'BaseUrl', 'VARCHAR', true, 300);

		$tMap->addColumn('REFILL', 'Refill', 'VARCHAR', true, 400);

		$tMap->addColumn('CALLING_CODE', 'CallingCode', 'VARCHAR', true, 50);

		$tMap->addColumn('CBF_RATE', 'CbfRate', 'FLOAT', true, null);

	} // doBuild()

} // EnableCountryMapBuilder
