<?php


/**
 * This class adds structure of 'getrefferredtransactionforextrarefills' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 12/30/11 11:22:06
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class GetrefferredtransactionforextrarefillsMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.GetrefferredtransactionforextrarefillsMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(GetrefferredtransactionforextrarefillsPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(GetrefferredtransactionforextrarefillsPeer::TABLE_NAME);
		$tMap->setPhpName('Getrefferredtransactionforextrarefills');
		$tMap->setClassname('Getrefferredtransactionforextrarefills');

		$tMap->setUseIdGenerator(true);

		$tMap->addColumn('AMOUNT', 'Amount', 'DECIMAL', false, 41);

		$tMap->addColumn('AMOUNT_CUR_MONTH', 'AmountCurMonth', 'DECIMAL', false, 41);

		$tMap->addColumn('CUSTOMER_ID', 'CustomerId', 'BIGINT', false, 20);

		$tMap->addColumn('REFERRER_ID', 'ReferrerId', 'INTEGER', false, 11);

		$tMap->addColumn('ERE_TODATE', 'EreTodate', 'DOUBLE', false, null);

		$tMap->addColumn('ERE_CUR_MONTH', 'EreCurMonth', 'DOUBLE', false, null);

		$tMap->addColumn('TOTAL_TRANSACTIONS', 'TotalTransactions', 'BIGINT', true, 21);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

	} // doBuild()

} // GetrefferredtransactionforextrarefillsMapBuilder
