<?php


/**
 * This class adds structure of 'sale_activity' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 01/11/12 05:25:25
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class SaleActivityMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.SaleActivityMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(SaleActivityPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(SaleActivityPeer::TABLE_NAME);
		$tMap->setPhpName('SaleActivity');
		$tMap->setClassname('SaleActivity');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11);

		$tMap->addForeignKey('COMPANY_ID', 'CompanyId', 'INTEGER', 'company', 'ID', false, 11);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('TICKET_NUMBER', 'TicketNumber', 'INTEGER', true, 11);

		$tMap->addForeignKey('SALE_ACTION_ID', 'SaleActionId', 'INTEGER', 'sale_action', 'ID', false, 11);

		$tMap->addColumn('COMMENT', 'Comment', 'LONGVARCHAR', true, null);

		$tMap->addColumn('FILE_PATH', 'FilePath', 'VARCHAR', false, 255);

		$tMap->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'user', 'ID', false, 11);

		$tMap->addForeignKey('SALE_ACTIVITY_STATUS_ID', 'SaleActivityStatusId', 'INTEGER', 'sale_activity_status', 'ID', false, 11);

	} // doBuild()

} // SaleActivityMapBuilder
