<?php

/**
 * Base class that represents a row from the 'package' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 12/30/11 11:22:07
 *
 * @package    lib.model.om
 */
abstract class BasePackage extends BaseObject  implements Persistent {


  const PEER = 'PackagePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PackagePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the billing_dur field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $billing_dur;

	/**
	 * The value for the billing_due_days field.
	 * @var        int
	 */
	protected $billing_due_days;

	/**
	 * The value for the specificatoin_cost field.
	 * @var        double
	 */
	protected $specificatoin_cost;

	/**
	 * The value for the r1_cost field.
	 * @var        double
	 */
	protected $r1_cost;

	/**
	 * The value for the r2_cost field.
	 * @var        double
	 */
	protected $r2_cost;

	/**
	 * The value for the activaton_cost field.
	 * @var        double
	 */
	protected $activaton_cost;

	/**
	 * The value for the created_at field.
	 * Note: this column has a database default value of: (expression) CURRENT_TIMESTAMP
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        array Company[] Collection to store aggregation of Company objects.
	 */
	protected $collCompanys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCompanys.
	 */
	private $lastCompanyCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasePackage object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->billing_dur = 1;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [billing_dur] column value.
	 * 
	 * @return     int
	 */
	public function getBillingDur()
	{
		return $this->billing_dur;
	}

	/**
	 * Get the [billing_due_days] column value.
	 * 
	 * @return     int
	 */
	public function getBillingDueDays()
	{
		return $this->billing_due_days;
	}

	/**
	 * Get the [specificatoin_cost] column value.
	 * 
	 * @return     double
	 */
	public function getSpecificatoinCost()
	{
		return $this->specificatoin_cost;
	}

	/**
	 * Get the [r1_cost] column value.
	 * 
	 * @return     double
	 */
	public function getR1Cost()
	{
		return $this->r1_cost;
	}

	/**
	 * Get the [r2_cost] column value.
	 * 
	 * @return     double
	 */
	public function getR2Cost()
	{
		return $this->r2_cost;
	}

	/**
	 * Get the [activaton_cost] column value.
	 * 
	 * @return     double
	 */
	public function getActivatonCost()
	{
		return $this->activaton_cost;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Package The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PackagePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Package The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = PackagePeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [billing_dur] column.
	 * 
	 * @param      int $v new value
	 * @return     Package The current object (for fluent API support)
	 */
	public function setBillingDur($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->billing_dur !== $v || $v === 1) {
			$this->billing_dur = $v;
			$this->modifiedColumns[] = PackagePeer::BILLING_DUR;
		}

		return $this;
	} // setBillingDur()

	/**
	 * Set the value of [billing_due_days] column.
	 * 
	 * @param      int $v new value
	 * @return     Package The current object (for fluent API support)
	 */
	public function setBillingDueDays($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->billing_due_days !== $v) {
			$this->billing_due_days = $v;
			$this->modifiedColumns[] = PackagePeer::BILLING_DUE_DAYS;
		}

		return $this;
	} // setBillingDueDays()

	/**
	 * Set the value of [specificatoin_cost] column.
	 * 
	 * @param      double $v new value
	 * @return     Package The current object (for fluent API support)
	 */
	public function setSpecificatoinCost($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->specificatoin_cost !== $v) {
			$this->specificatoin_cost = $v;
			$this->modifiedColumns[] = PackagePeer::SPECIFICATOIN_COST;
		}

		return $this;
	} // setSpecificatoinCost()

	/**
	 * Set the value of [r1_cost] column.
	 * 
	 * @param      double $v new value
	 * @return     Package The current object (for fluent API support)
	 */
	public function setR1Cost($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->r1_cost !== $v) {
			$this->r1_cost = $v;
			$this->modifiedColumns[] = PackagePeer::R1_COST;
		}

		return $this;
	} // setR1Cost()

	/**
	 * Set the value of [r2_cost] column.
	 * 
	 * @param      double $v new value
	 * @return     Package The current object (for fluent API support)
	 */
	public function setR2Cost($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->r2_cost !== $v) {
			$this->r2_cost = $v;
			$this->modifiedColumns[] = PackagePeer::R2_COST;
		}

		return $this;
	} // setR2Cost()

	/**
	 * Set the value of [activaton_cost] column.
	 * 
	 * @param      double $v new value
	 * @return     Package The current object (for fluent API support)
	 */
	public function setActivatonCost($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->activaton_cost !== $v) {
			$this->activaton_cost = $v;
			$this->modifiedColumns[] = PackagePeer::ACTIVATON_COST;
		}

		return $this;
	} // setActivatonCost()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Package The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PackagePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Package The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = PackagePeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(PackagePeer::BILLING_DUR))) {
				return false;
			}

			if ($this->billing_dur !== 1) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->billing_dur = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->billing_due_days = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->specificatoin_cost = ($row[$startcol + 4] !== null) ? (double) $row[$startcol + 4] : null;
			$this->r1_cost = ($row[$startcol + 5] !== null) ? (double) $row[$startcol + 5] : null;
			$this->r2_cost = ($row[$startcol + 6] !== null) ? (double) $row[$startcol + 6] : null;
			$this->activaton_cost = ($row[$startcol + 7] !== null) ? (double) $row[$startcol + 7] : null;
			$this->created_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->updated_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = PackagePeer::NUM_COLUMNS - PackagePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Package object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PackagePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PackagePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collCompanys = null;
			$this->lastCompanyCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePackage:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PackagePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			PackagePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasePackage:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasePackage:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(PackagePeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(PackagePeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PackagePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasePackage:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			PackagePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PackagePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PackagePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PackagePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCompanys !== null) {
				foreach ($this->collCompanys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = PackagePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCompanys !== null) {
					foreach ($this->collCompanys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PackagePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getBillingDur();
				break;
			case 3:
				return $this->getBillingDueDays();
				break;
			case 4:
				return $this->getSpecificatoinCost();
				break;
			case 5:
				return $this->getR1Cost();
				break;
			case 6:
				return $this->getR2Cost();
				break;
			case 7:
				return $this->getActivatonCost();
				break;
			case 8:
				return $this->getCreatedAt();
				break;
			case 9:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PackagePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getBillingDur(),
			$keys[3] => $this->getBillingDueDays(),
			$keys[4] => $this->getSpecificatoinCost(),
			$keys[5] => $this->getR1Cost(),
			$keys[6] => $this->getR2Cost(),
			$keys[7] => $this->getActivatonCost(),
			$keys[8] => $this->getCreatedAt(),
			$keys[9] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PackagePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setBillingDur($value);
				break;
			case 3:
				$this->setBillingDueDays($value);
				break;
			case 4:
				$this->setSpecificatoinCost($value);
				break;
			case 5:
				$this->setR1Cost($value);
				break;
			case 6:
				$this->setR2Cost($value);
				break;
			case 7:
				$this->setActivatonCost($value);
				break;
			case 8:
				$this->setCreatedAt($value);
				break;
			case 9:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PackagePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setBillingDur($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setBillingDueDays($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setSpecificatoinCost($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setR1Cost($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setR2Cost($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setActivatonCost($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCreatedAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUpdatedAt($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PackagePeer::DATABASE_NAME);

		if ($this->isColumnModified(PackagePeer::ID)) $criteria->add(PackagePeer::ID, $this->id);
		if ($this->isColumnModified(PackagePeer::NAME)) $criteria->add(PackagePeer::NAME, $this->name);
		if ($this->isColumnModified(PackagePeer::BILLING_DUR)) $criteria->add(PackagePeer::BILLING_DUR, $this->billing_dur);
		if ($this->isColumnModified(PackagePeer::BILLING_DUE_DAYS)) $criteria->add(PackagePeer::BILLING_DUE_DAYS, $this->billing_due_days);
		if ($this->isColumnModified(PackagePeer::SPECIFICATOIN_COST)) $criteria->add(PackagePeer::SPECIFICATOIN_COST, $this->specificatoin_cost);
		if ($this->isColumnModified(PackagePeer::R1_COST)) $criteria->add(PackagePeer::R1_COST, $this->r1_cost);
		if ($this->isColumnModified(PackagePeer::R2_COST)) $criteria->add(PackagePeer::R2_COST, $this->r2_cost);
		if ($this->isColumnModified(PackagePeer::ACTIVATON_COST)) $criteria->add(PackagePeer::ACTIVATON_COST, $this->activaton_cost);
		if ($this->isColumnModified(PackagePeer::CREATED_AT)) $criteria->add(PackagePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(PackagePeer::UPDATED_AT)) $criteria->add(PackagePeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PackagePeer::DATABASE_NAME);

		$criteria->add(PackagePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Package (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setBillingDur($this->billing_dur);

		$copyObj->setBillingDueDays($this->billing_due_days);

		$copyObj->setSpecificatoinCost($this->specificatoin_cost);

		$copyObj->setR1Cost($this->r1_cost);

		$copyObj->setR2Cost($this->r2_cost);

		$copyObj->setActivatonCost($this->activaton_cost);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCompanys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCompany($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Package Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PackagePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PackagePeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collCompanys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCompanys()
	 */
	public function clearCompanys()
	{
		$this->collCompanys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCompanys collection (array).
	 *
	 * By default this just sets the collCompanys collection to an empty array (like clearcollCompanys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCompanys()
	{
		$this->collCompanys = array();
	}

	/**
	 * Gets an array of Company objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Package has previously been saved, it will retrieve
	 * related Companys from storage. If this Package is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Company[]
	 * @throws     PropelException
	 */
	public function getCompanys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
			   $this->collCompanys = array();
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				CompanyPeer::addSelectColumns($criteria);
				$this->collCompanys = CompanyPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				CompanyPeer::addSelectColumns($criteria);
				if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
					$this->collCompanys = CompanyPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCompanyCriteria = $criteria;
		return $this->collCompanys;
	}

	/**
	 * Returns the number of related Company objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Company objects.
	 * @throws     PropelException
	 */
	public function countCompanys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				$count = CompanyPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
					$count = CompanyPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCompanys);
				}
			} else {
				$count = count($this->collCompanys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Company object to this object
	 * through the Company foreign key attribute.
	 *
	 * @param      Company $l Company
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCompany(Company $l)
	{
		if ($this->collCompanys === null) {
			$this->initCompanys();
		}
		if (!in_array($l, $this->collCompanys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCompanys, $l);
			$l->setPackage($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Package is new, it will return
	 * an empty collection; or if this Package has previously
	 * been saved, it will retrieve related Companys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Package.
	 */
	public function getCompanysJoinCountry($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
				$this->collCompanys = array();
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				$this->collCompanys = CompanyPeer::doSelectJoinCountry($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

			if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
				$this->collCompanys = CompanyPeer::doSelectJoinCountry($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompanyCriteria = $criteria;

		return $this->collCompanys;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Package is new, it will return
	 * an empty collection; or if this Package has previously
	 * been saved, it will retrieve related Companys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Package.
	 */
	public function getCompanysJoinCity($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
				$this->collCompanys = array();
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				$this->collCompanys = CompanyPeer::doSelectJoinCity($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

			if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
				$this->collCompanys = CompanyPeer::doSelectJoinCity($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompanyCriteria = $criteria;

		return $this->collCompanys;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Package is new, it will return
	 * an empty collection; or if this Package has previously
	 * been saved, it will retrieve related Companys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Package.
	 */
	public function getCompanysJoinStatus($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
				$this->collCompanys = array();
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				$this->collCompanys = CompanyPeer::doSelectJoinStatus($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

			if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
				$this->collCompanys = CompanyPeer::doSelectJoinStatus($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompanyCriteria = $criteria;

		return $this->collCompanys;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Package is new, it will return
	 * an empty collection; or if this Package has previously
	 * been saved, it will retrieve related Companys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Package.
	 */
	public function getCompanysJoinCompanySize($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
				$this->collCompanys = array();
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				$this->collCompanys = CompanyPeer::doSelectJoinCompanySize($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

			if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
				$this->collCompanys = CompanyPeer::doSelectJoinCompanySize($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompanyCriteria = $criteria;

		return $this->collCompanys;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Package is new, it will return
	 * an empty collection; or if this Package has previously
	 * been saved, it will retrieve related Companys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Package.
	 */
	public function getCompanysJoinCompanyType($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
				$this->collCompanys = array();
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				$this->collCompanys = CompanyPeer::doSelectJoinCompanyType($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

			if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
				$this->collCompanys = CompanyPeer::doSelectJoinCompanyType($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompanyCriteria = $criteria;

		return $this->collCompanys;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Package is new, it will return
	 * an empty collection; or if this Package has previously
	 * been saved, it will retrieve related Companys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Package.
	 */
	public function getCompanysJoinCustomerType($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
				$this->collCompanys = array();
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				$this->collCompanys = CompanyPeer::doSelectJoinCustomerType($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

			if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
				$this->collCompanys = CompanyPeer::doSelectJoinCustomerType($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompanyCriteria = $criteria;

		return $this->collCompanys;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Package is new, it will return
	 * an empty collection; or if this Package has previously
	 * been saved, it will retrieve related Companys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Package.
	 */
	public function getCompanysJoinApartmentForm($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
				$this->collCompanys = array();
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				$this->collCompanys = CompanyPeer::doSelectJoinApartmentForm($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

			if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
				$this->collCompanys = CompanyPeer::doSelectJoinApartmentForm($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompanyCriteria = $criteria;

		return $this->collCompanys;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Package is new, it will return
	 * an empty collection; or if this Package has previously
	 * been saved, it will retrieve related Companys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Package.
	 */
	public function getCompanysJoinInvoiceMethod($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
				$this->collCompanys = array();
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				$this->collCompanys = CompanyPeer::doSelectJoinInvoiceMethod($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

			if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
				$this->collCompanys = CompanyPeer::doSelectJoinInvoiceMethod($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompanyCriteria = $criteria;

		return $this->collCompanys;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Package is new, it will return
	 * an empty collection; or if this Package has previously
	 * been saved, it will retrieve related Companys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Package.
	 */
	public function getCompanysJoinUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
				$this->collCompanys = array();
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				$this->collCompanys = CompanyPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

			if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
				$this->collCompanys = CompanyPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompanyCriteria = $criteria;

		return $this->collCompanys;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Package is new, it will return
	 * an empty collection; or if this Package has previously
	 * been saved, it will retrieve related Companys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Package.
	 */
	public function getCompanysJoinAgentCompany($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PackagePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCompanys === null) {
			if ($this->isNew()) {
				$this->collCompanys = array();
			} else {

				$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

				$this->collCompanys = CompanyPeer::doSelectJoinAgentCompany($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CompanyPeer::PACKAGE_ID, $this->id);

			if (!isset($this->lastCompanyCriteria) || !$this->lastCompanyCriteria->equals($criteria)) {
				$this->collCompanys = CompanyPeer::doSelectJoinAgentCompany($criteria, $con, $join_behavior);
			}
		}
		$this->lastCompanyCriteria = $criteria;

		return $this->collCompanys;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCompanys) {
				foreach ((array) $this->collCompanys as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCompanys = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasePackage:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasePackage::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasePackage
