<?php

/**
 * Base static class for performing query and update operations on the 'companies_customers$' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 05/10/10 11:08:19
 *
 * @package    lib.model.om
 */
abstract class BaseCompaniesCustomers$Peer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'companies_customers$';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.CompaniesCustomers$';

	/** The total number of columns. */
	const NUM_COLUMNS = 29;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'companies_customers$.ID';

	/** the column name for the NAME field */
	const NAME = 'companies_customers$.NAME';

	/** the column name for the VAT_NO field */
	const VAT_NO = 'companies_customers$.VAT_NO';

	/** the column name for the EAN_NUMBER field */
	const EAN_NUMBER = 'companies_customers$.EAN_NUMBER';

	/** the column name for the ADDRESS field */
	const ADDRESS = 'companies_customers$.ADDRESS';

	/** the column name for the POST_CODE field */
	const POST_CODE = 'companies_customers$.POST_CODE';

	/** the column name for the COUNTRY_ID field */
	const COUNTRY_ID = 'companies_customers$.COUNTRY_ID';

	/** the column name for the CITY_ID field */
	const CITY_ID = 'companies_customers$.CITY_ID';

	/** the column name for the CONTACT_NAME field */
	const CONTACT_NAME = 'companies_customers$.CONTACT_NAME';

	/** the column name for the EMAIL field */
	const EMAIL = 'companies_customers$.EMAIL';

	/** the column name for the HEAD_PHONE_NUMBER field */
	const HEAD_PHONE_NUMBER = 'companies_customers$.HEAD_PHONE_NUMBER';

	/** the column name for the FAX_NUMBER field */
	const FAX_NUMBER = 'companies_customers$.FAX_NUMBER';

	/** the column name for the WEBSITE field */
	const WEBSITE = 'companies_customers$.WEBSITE';

	/** the column name for the STATUS_ID field */
	const STATUS_ID = 'companies_customers$.STATUS_ID';

	/** the column name for the COMPANY_SIZE_ID field */
	const COMPANY_SIZE_ID = 'companies_customers$.COMPANY_SIZE_ID';

	/** the column name for the COMPANY_TYPE_ID field */
	const COMPANY_TYPE_ID = 'companies_customers$.COMPANY_TYPE_ID';

	/** the column name for the CUSTOMER_TYPE_ID field */
	const CUSTOMER_TYPE_ID = 'companies_customers$.CUSTOMER_TYPE_ID';

	/** the column name for the CPR_NUMBER field */
	const CPR_NUMBER = 'companies_customers$.CPR_NUMBER';

	/** the column name for the APARTMENT_FORM_ID field */
	const APARTMENT_FORM_ID = 'companies_customers$.APARTMENT_FORM_ID';

	/** the column name for the INVOICE_METHOD_ID field */
	const INVOICE_METHOD_ID = 'companies_customers$.INVOICE_METHOD_ID';

	/** the column name for the ACCOUNT_MANAGER_ID field */
	const ACCOUNT_MANAGER_ID = 'companies_customers$.ACCOUNT_MANAGER_ID';

	/** the column name for the AGENT_COMPANY_ID field */
	const AGENT_COMPANY_ID = 'companies_customers$.AGENT_COMPANY_ID';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'companies_customers$.CREATED_AT';

	/** the column name for the CONFIRMED_AT field */
	const CONFIRMED_AT = 'companies_customers$.CONFIRMED_AT';

	/** the column name for the CVR_NUMBER field */
	const CVR_NUMBER = 'companies_customers$.CVR_NUMBER';

	/** the column name for the SIM_CARD_DISPATCH_DATE field */
	const SIM_CARD_DISPATCH_DATE = 'companies_customers$.SIM_CARD_DISPATCH_DATE';

	/** the column name for the PACKAGE_ID field */
	const PACKAGE_ID = 'companies_customers$.PACKAGE_ID';

	/** the column name for the REGISTRATION_DISCOUNT_PC field */
	const REGISTRATION_DISCOUNT_PC = 'companies_customers$.REGISTRATION_DISCOUNT_PC';

	/** the column name for the USAGE_DISCOUNT_PC field */
	const USAGE_DISCOUNT_PC = 'companies_customers$.USAGE_DISCOUNT_PC';

	/**
	 * An identiy map to hold any loaded instances of CompaniesCustomers$ objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array CompaniesCustomers$[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Name', 'VatNo', 'EanNumber', 'Address', 'PostCode', 'CountryId', 'CityId', 'ContactName', 'Email', 'HeadPhoneNumber', 'FaxNumber', 'Website', 'StatusId', 'CompanySizeId', 'CompanyTypeId', 'CustomerTypeId', 'CprNumber', 'ApartmentFormId', 'InvoiceMethodId', 'AccountManagerId', 'AgentCompanyId', 'CreatedAt', 'ConfirmedAt', 'CvrNumber', 'SimCardDispatchDate', 'PackageId', 'RegistrationDiscountPc', 'UsageDiscountPc', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'name', 'vatNo', 'eanNumber', 'address', 'postCode', 'countryId', 'cityId', 'contactName', 'email', 'headPhoneNumber', 'faxNumber', 'website', 'statusId', 'companySizeId', 'companyTypeId', 'customerTypeId', 'cprNumber', 'apartmentFormId', 'invoiceMethodId', 'accountManagerId', 'agentCompanyId', 'createdAt', 'confirmedAt', 'cvrNumber', 'simCardDispatchDate', 'packageId', 'registrationDiscountPc', 'usageDiscountPc', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::NAME, self::VAT_NO, self::EAN_NUMBER, self::ADDRESS, self::POST_CODE, self::COUNTRY_ID, self::CITY_ID, self::CONTACT_NAME, self::EMAIL, self::HEAD_PHONE_NUMBER, self::FAX_NUMBER, self::WEBSITE, self::STATUS_ID, self::COMPANY_SIZE_ID, self::COMPANY_TYPE_ID, self::CUSTOMER_TYPE_ID, self::CPR_NUMBER, self::APARTMENT_FORM_ID, self::INVOICE_METHOD_ID, self::ACCOUNT_MANAGER_ID, self::AGENT_COMPANY_ID, self::CREATED_AT, self::CONFIRMED_AT, self::CVR_NUMBER, self::SIM_CARD_DISPATCH_DATE, self::PACKAGE_ID, self::REGISTRATION_DISCOUNT_PC, self::USAGE_DISCOUNT_PC, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'name', 'vat_no', 'ean_number', 'address', 'post_code', 'country_id', 'city_id', 'contact_name', 'email', 'head_phone_number', 'fax_number', 'website', 'status_id', 'company_size_id', 'company_type_id', 'customer_type_id', 'cpr_number', 'apartment_form_id', 'invoice_method_id', 'account_manager_id', 'agent_company_id', 'created_at', 'confirmed_at', 'cvr_number', 'sim_card_dispatch_date', 'package_id', 'registration_discount_pc', 'usage_discount_pc', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Name' => 1, 'VatNo' => 2, 'EanNumber' => 3, 'Address' => 4, 'PostCode' => 5, 'CountryId' => 6, 'CityId' => 7, 'ContactName' => 8, 'Email' => 9, 'HeadPhoneNumber' => 10, 'FaxNumber' => 11, 'Website' => 12, 'StatusId' => 13, 'CompanySizeId' => 14, 'CompanyTypeId' => 15, 'CustomerTypeId' => 16, 'CprNumber' => 17, 'ApartmentFormId' => 18, 'InvoiceMethodId' => 19, 'AccountManagerId' => 20, 'AgentCompanyId' => 21, 'CreatedAt' => 22, 'ConfirmedAt' => 23, 'CvrNumber' => 24, 'SimCardDispatchDate' => 25, 'PackageId' => 26, 'RegistrationDiscountPc' => 27, 'UsageDiscountPc' => 28, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'name' => 1, 'vatNo' => 2, 'eanNumber' => 3, 'address' => 4, 'postCode' => 5, 'countryId' => 6, 'cityId' => 7, 'contactName' => 8, 'email' => 9, 'headPhoneNumber' => 10, 'faxNumber' => 11, 'website' => 12, 'statusId' => 13, 'companySizeId' => 14, 'companyTypeId' => 15, 'customerTypeId' => 16, 'cprNumber' => 17, 'apartmentFormId' => 18, 'invoiceMethodId' => 19, 'accountManagerId' => 20, 'agentCompanyId' => 21, 'createdAt' => 22, 'confirmedAt' => 23, 'cvrNumber' => 24, 'simCardDispatchDate' => 25, 'packageId' => 26, 'registrationDiscountPc' => 27, 'usageDiscountPc' => 28, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::NAME => 1, self::VAT_NO => 2, self::EAN_NUMBER => 3, self::ADDRESS => 4, self::POST_CODE => 5, self::COUNTRY_ID => 6, self::CITY_ID => 7, self::CONTACT_NAME => 8, self::EMAIL => 9, self::HEAD_PHONE_NUMBER => 10, self::FAX_NUMBER => 11, self::WEBSITE => 12, self::STATUS_ID => 13, self::COMPANY_SIZE_ID => 14, self::COMPANY_TYPE_ID => 15, self::CUSTOMER_TYPE_ID => 16, self::CPR_NUMBER => 17, self::APARTMENT_FORM_ID => 18, self::INVOICE_METHOD_ID => 19, self::ACCOUNT_MANAGER_ID => 20, self::AGENT_COMPANY_ID => 21, self::CREATED_AT => 22, self::CONFIRMED_AT => 23, self::CVR_NUMBER => 24, self::SIM_CARD_DISPATCH_DATE => 25, self::PACKAGE_ID => 26, self::REGISTRATION_DISCOUNT_PC => 27, self::USAGE_DISCOUNT_PC => 28, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'name' => 1, 'vat_no' => 2, 'ean_number' => 3, 'address' => 4, 'post_code' => 5, 'country_id' => 6, 'city_id' => 7, 'contact_name' => 8, 'email' => 9, 'head_phone_number' => 10, 'fax_number' => 11, 'website' => 12, 'status_id' => 13, 'company_size_id' => 14, 'company_type_id' => 15, 'customer_type_id' => 16, 'cpr_number' => 17, 'apartment_form_id' => 18, 'invoice_method_id' => 19, 'account_manager_id' => 20, 'agent_company_id' => 21, 'created_at' => 22, 'confirmed_at' => 23, 'cvr_number' => 24, 'sim_card_dispatch_date' => 25, 'package_id' => 26, 'registration_discount_pc' => 27, 'usage_discount_pc' => 28, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new CompaniesCustomers$MapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. CompaniesCustomers$Peer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(CompaniesCustomers$Peer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(CompaniesCustomers$Peer::ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::NAME);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::VAT_NO);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::EAN_NUMBER);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::ADDRESS);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::POST_CODE);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::COUNTRY_ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::CITY_ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::CONTACT_NAME);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::EMAIL);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::HEAD_PHONE_NUMBER);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::FAX_NUMBER);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::WEBSITE);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::STATUS_ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::COMPANY_SIZE_ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::COMPANY_TYPE_ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::CUSTOMER_TYPE_ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::CPR_NUMBER);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::APARTMENT_FORM_ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::INVOICE_METHOD_ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::ACCOUNT_MANAGER_ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::AGENT_COMPANY_ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::CREATED_AT);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::CONFIRMED_AT);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::CVR_NUMBER);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::SIM_CARD_DISPATCH_DATE);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::PACKAGE_ID);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::REGISTRATION_DISCOUNT_PC);

		$criteria->addSelectColumn(CompaniesCustomers$Peer::USAGE_DISCOUNT_PC);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CompaniesCustomers$Peer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CompaniesCustomers$Peer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(CompaniesCustomers$Peer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseCompaniesCustomers$Peer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCompaniesCustomers$Peer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     CompaniesCustomers$
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = CompaniesCustomers$Peer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return CompaniesCustomers$Peer::populateObjects(CompaniesCustomers$Peer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCompaniesCustomers$Peer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseCompaniesCustomers$Peer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(CompaniesCustomers$Peer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			CompaniesCustomers$Peer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      CompaniesCustomers$ $value A CompaniesCustomers$ object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(CompaniesCustomers$ $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A CompaniesCustomers$ object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof CompaniesCustomers$) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or CompaniesCustomers$ object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     CompaniesCustomers$ Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = CompaniesCustomers$Peer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = CompaniesCustomers$Peer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = CompaniesCustomers$Peer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				CompaniesCustomers$Peer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return CompaniesCustomers$Peer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a CompaniesCustomers$ or Criteria object.
	 *
	 * @param      mixed $values Criteria or CompaniesCustomers$ object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCompaniesCustomers$Peer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseCompaniesCustomers$Peer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(CompaniesCustomers$Peer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from CompaniesCustomers$ object
		}

		if ($criteria->containsKey(CompaniesCustomers$Peer::ID) && $criteria->keyContainsValue(CompaniesCustomers$Peer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.CompaniesCustomers$Peer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseCompaniesCustomers$Peer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseCompaniesCustomers$Peer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a CompaniesCustomers$ or Criteria object.
	 *
	 * @param      mixed $values Criteria or CompaniesCustomers$ object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCompaniesCustomers$Peer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseCompaniesCustomers$Peer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(CompaniesCustomers$Peer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(CompaniesCustomers$Peer::ID);
			$selectCriteria->add(CompaniesCustomers$Peer::ID, $criteria->remove(CompaniesCustomers$Peer::ID), $comparison);

		} else { // $values is CompaniesCustomers$ object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseCompaniesCustomers$Peer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseCompaniesCustomers$Peer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the companies_customers$ table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CompaniesCustomers$Peer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(CompaniesCustomers$Peer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a CompaniesCustomers$ or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or CompaniesCustomers$ object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(CompaniesCustomers$Peer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			CompaniesCustomers$Peer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof CompaniesCustomers$) {
			// invalidate the cache for this single object
			CompaniesCustomers$Peer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(CompaniesCustomers$Peer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				CompaniesCustomers$Peer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given CompaniesCustomers$ object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      CompaniesCustomers$ $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(CompaniesCustomers$ $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(CompaniesCustomers$Peer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(CompaniesCustomers$Peer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(CompaniesCustomers$Peer::DATABASE_NAME, CompaniesCustomers$Peer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = CompaniesCustomers$Peer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     CompaniesCustomers$
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = CompaniesCustomers$Peer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(CompaniesCustomers$Peer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(CompaniesCustomers$Peer::DATABASE_NAME);
		$criteria->add(CompaniesCustomers$Peer::ID, $pk);

		$v = CompaniesCustomers$Peer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CompaniesCustomers$Peer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(CompaniesCustomers$Peer::DATABASE_NAME);
			$criteria->add(CompaniesCustomers$Peer::ID, $pks, Criteria::IN);
			$objs = CompaniesCustomers$Peer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseCompaniesCustomers$Peer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the CompaniesCustomers$Peer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the CompaniesCustomers$Peer class:
//
// Propel::getDatabaseMap(CompaniesCustomers$Peer::DATABASE_NAME)->addTableBuilder(CompaniesCustomers$Peer::TABLE_NAME, CompaniesCustomers$Peer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseCompaniesCustomers$Peer::DATABASE_NAME)->addTableBuilder(BaseCompaniesCustomers$Peer::TABLE_NAME, BaseCompaniesCustomers$Peer::getMapBuilder());

