generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      AgentCommissionPackage
    theme:            default
    css:             /sf/sf_admin/css/admin_main.css
    list:
      title: Agent Commission Package List
      display: [name, reg_share_value, is_reg_share_value_pc, extra_payments_share_value, is_extra_payments_share_value_pc]
      fields:
        is_reg_share_value_pc: {name: Is Reg. share value %}
        is_extra_payments_share_value_pc: {name: Is extra refill share value %}
      object_actions:
        _delete: ~
    edit:
      title: create/edit agent commission package
      fields:
        is_reg_share_value_pc: {name: Is Reg. share value %}
        is_extra_payments_share_value_pc: {name: Is extra refill share value %}