generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      UsageAlert
    theme:            default
    list:
            title: 'Usage Alert'
            object_actions:
              _delete: ~
              _edit: ~