generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      UsageAlert
    theme:            default
    css:             /sf/sf_admin/css/admin_main.css
    list:
            title: 'Low Credit Alert'
            display: [id, alert_amount_min, alert_amount_max, sms_alert_message, sms_active, email_alert_message, email_active, enable_country, usage_alert_sender, status]
            fields:
              enable_country: {name: Country}
              usage_alert_sender: {name: Sender Name}
            object_actions:
              _delete: ~
              _edit: ~
    edit:
            title: 'Edit Low Credit Alert'