generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      UsageAlert
    theme:            default
    css:             /sf/sf_admin/css/admin_main.css
    list:
            title: 'Usage Alert'
            object_actions:
              _delete: ~
              _edit: ~