generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      SaleActivityStatus
    theme:            default
    
    list:
      title: 'Sale Activty Statuses'
      display: [name]
      object_actions:
        _edit: ~
        _delete: ~
    edit:
      title: 'Create/Edit Sale Activty Status'
      display: [name]
