generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      UsageAlertSender
    theme:            default
    css:             /sf/sf_admin/css/admin_main.css
    list:
            title: 'Low Credit Alert Sender'
            display: [id, name]
    edit:
            title: 'Edit Low Credit Alert Sender'
            display: [id, name]