generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Package
    theme:            default
    list:
      display:  [name]
      object_actions:
       _edit:  ~
       _delete:  ~
    
    
