generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      AgentUser
    theme:            default
    css:             /sf/sf_admin/css/admin_main.css
    list:
      display: [id, agent_company, username, password, status]
      object_actions:
        _delete: ~
