generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      EnableCountry
    theme:            default
    css:             /sf/sf_admin/css/admin_main.css

    fields:
      language_symbol:     { name: Language Symbol }
      refill:    { help: Refill Amount Must be Comma Separate }

    edit:
      title: Create/Edit Country
      display: [name, language, language_symbol]

    list:
      display: [name, language, language_symbol]
      max_per_page: 100
      object_actions:
        _edit: ~
        _delete: ~