dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=localhost;dbname=landncall'
      username: root
      password: 1Qazxsw@
      encoding: utf8
      persistent: true
      pooling: true
