generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      User
    theme:            default
    
    list:
      display: [name, email, password, role, is_super_user, created_at]
      object_actions:
        _edit: ~
