default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, style.css, 960.css]

  javascripts:    [jquery-1.4.2.min.js, /sf/prototype/js/prototype.js, jquery.formatCurrency-1.3.0.min.js, i18n/jquery.formatCurrency.all.js ,jquery.validate.js]

  has_layout:     on
  layout:         layout
