generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Company
    theme:            default
    fields:
      head_phone_number: {label: head phone nr}
      name: {label: Company Name}
    list:
      filters: [_company_name, vat_no]
      display: [name, vat_no, contact_name, head_phone_number, confirmed_at, sim_card_dispatch_date, _action_generate_invoice]
      fields:
        action_generate_invoice: {name: Invoice}
        name: {name: Company Name}
      max_per_page: 1000
      object_actions:
        _edit: ~
        _delete: ~
        view: {label: view details, action:view}
    edit:
      title:  Create/Edit Company
      display:  ~
      fields:
        file_path:
          name:       Registration Doc
          type:       admin_input_file_tag
          params:     include_link=/ include_remove=true